//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP_KR_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class messagee
    {
        public int code_f { get; set; }
        public int code_w { get; set; }
        public string texxt { get; set; }
    
        public virtual fromm fromm { get; set; }
        public virtual whom whom { get; set; }
    }
}
